[features]
seeds = false
skip-lint = false
[programs.localnet]
# Need to update these IDs after the first deployment to localnet (e.g. by running scripts/update-anchor-toml.sh).
sollery = "25to815MeTgAP5q87EkbSFqBh1XgL2AR6DZwHNKyEGkX"
calculator = "F71MP2c2WXJC6mMpCk3TdCjGRekmRVQ9foEqzPkz9ZCL"

[registry]
#url = "https://anchor.projectserum.com"
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json" # Changed from '/Users/<user>' to '~'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Added this section, because 'anchor run test' was trying to connect to ::1 instead of 127.0.0.1. See https://book.anchor-lang.com/anchor_references/anchor-toml_reference.html#testvalidator
[test.validator]
bind_address = "127.0.0.1"
